Controlled accounts
immers-space/immers pull request #55
Opened 2022-04-06 13:51 UTC by wmurphyrd

2022-05-11 01:31 UTC, wmurphyrd commented on src/authdb.js
> +    }
This allows creating user without password, [existing code](https://github.com/immers-space/immers/blob/controlled-accounts/src/authdb.js#L64) in `validateUser` already checks and rejects authentication requests when the user has no saved password

2022-05-14 15:40 UTC, wmurphyrd commented
It just hit me the way I should have done the user registration override.
1. Leave the existing route and settings methods unchanged
2. Put another POST /auth/user before the original that checks for the presence of a bearer token, authorizes with it if so,  and passes onto the original route with next('route') if not

Gonna draft this PR and go back and do it that way

2022-05-17 20:38 UTC, quinn-madson requested changes

2022-05-17 20:38 UTC, quinn-madson commented on doc/ControlledAccounts.md
> +const auth = jwt.sign(
I think this is supposed to be: **oAuthJwt** instead of **auth**.

2022-05-17 20:38 UTC, quinn-madson commented on doc/ControlledAccounts.md
> +const params = new url.URLSearchParams({
I don't think params is being used here.

2022-05-17 23:02 UTC, quinn-madson approved these changes

2022-05-17 23:02 UTC, merged